language: node_js
os:
  - linux
sudo: false
node_js:
  - "stable"
  - "4.2"
  - "4.1"
  - "4.0"
script:
- npm run ci-build
before_script:
- npm install
- git config --global user.email "travis-ci-build@volusion.com"
- git config --global user.name "Travis CI Build"
